### ISSUE TITLE
用上海的区定位会包括苏州和杭州的门店，可以指定门店盯库存吗？

### ISSUE THREAD

**Issue by BananaDogg** [ToolGallery/APEStoreAssistant#10]
![iShot_2023-09-22_14 07 27](https://github.com/ToolGallery/APEStoreAssistant/assets/145745498/d88071a8-a2d5-4dd6-b8c6-06ebc212095f)

**Comment by FreeIdom** [comment]
可以，我加个参数

**Comment by FreeIdom** [comment]
已加，通过 `-sft` 参数指定筛选名称

**Comment by rzjsbbbb** [comment]
怎么筛选多个店铺？比如想要同时苏州无锡 -sft "苏州","无锡“木有用

**Comment by vijosam** [comment]
> 怎么筛选多个店铺？比如想要同时苏州无锡 -sft "苏州","无锡“木有用

输店铺名，不是城市名

**Comment by rzjsbbbb** [comment]
> > 怎么筛选多个店铺？比如想要同时苏州无锡 -sft "苏州","无锡“木有用
> 
> 输店铺名，不是城市名

-sft "无锡恒隆广场”,"苏州"
2023-09-23 14:53:07,521.521 INFO inventory_monitoring - start: Start monitoring, query interval: 5s
2023-09-23 14:53:08,704.704 WARNING inventory_monitoring - start: No available stores found
依旧

**Comment by vijosam** [comment]
> > > 怎么筛选多个店铺？比如想要同时苏州无锡 -sft "苏州","无锡“木有用
> > 
> > 
> > 输店铺名，不是城市名
> 
> -sft "无锡恒隆广场”,"苏州" 2023-09-23 14:53:07,521.521 INFO inventory_monitoring - start: Start monitoring, query interval: 5s 2023-09-23 14:53:08,704.704 WARNING inventory_monitoring - start: No available stores found 依旧

不要用逗号，用空格

`docker run --rm toolgallery/ape-store-assistant:main -c cn -p MU2Q3CH/A -l "浙江 杭州 上城区" --code 15-pro -sft "无锡恒隆广场" "苏州"`

**Comment by rzjsbbbb** [comment]
```
2023-09-23 23:58:11,235.235 ERROR inventory_monitoring - start: Failed to retrieve inventory data with error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/actions/inventory_monitoring.py", line 44, in start
    inventory_data = self.get_data(
  File "/app/actions/inventory_monitoring.py", line 164, in get_data
    return resp.json()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)``
```

跑着跑着就会冒个错误

**Comment by kumatang** [comment]
> ```
> 2023-09-23 23:58:11,235.235 ERROR inventory_monitoring - start: Failed to retrieve inventory data with error:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/app/actions/inventory_monitoring.py", line 44, in start
>     inventory_data = self.get_data(
>   File "/app/actions/inventory_monitoring.py", line 164, in get_data
>     return resp.json()
>   File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
>     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
> requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)``
> ```
> 
> 跑着跑着就会冒个错误

看起来是刷新太频繁了，试试增加刷新间隔

**Comment by BananaDogg** [comment]
> > ```
> > 2023-09-23 23:58:11,235.235 ERROR inventory_monitoring - start: Failed to retrieve inventory data with error:
> > Traceback (most recent call last):
> >   File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
> >     return complexjson.loads(self.text, **kwargs)
> >   File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
> >     return _default_decoder.decode(s)
> >   File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
> >     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> >   File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
> >     raise JSONDecodeError("Expecting value", s, err.value) from None
> > json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> > 
> > During handling of the above exception, another exception occurred:
> > 
> > Traceback (most recent call last):
> >   File "/app/actions/inventory_monitoring.py", line 44, in start
> >     inventory_data = self.get_data(
> >   File "/app/actions/inventory_monitoring.py", line 164, in get_data
> >     return resp.json()
> >   File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
> >     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
> > requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)``
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 跑着跑着就会冒个错误
> 
> 看起来是刷新太频繁了，试试增加刷新间隔

我也遇到这个错误，间隔调大了也没用，停了一段时间后运行第一次就这样报错

**Comment by rzjsbbbb** [comment]
> > > ```
> > > 2023-09-23 23:58:11,235.235 ERROR inventory_monitoring - start: Failed to retrieve inventory data with error:
> > > Traceback (most recent call last):
> > >   File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
> > >     return complexjson.loads(self.text, **kwargs)
> > >   File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
> > >     return _default_decoder.decode(s)
> > >   File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
> > >     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> > >   File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
> > >     raise JSONDecodeError("Expecting value", s, err.value) from None
> > > json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> > > 
> > > During handling of the above exception, another exception occurred:
> > > 
> > > Traceback (most recent call last):
> > >   File "/app/actions/inventory_monitoring.py", line 44, in start
> > >     inventory_data = self.get_data(
> > >   File "/app/actions/inventory_monitoring.py", line 164, in get_data
> > >     return resp.json()
> > >   File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
> > >     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
> > > requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)``
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 跑着跑着就会冒个错误
> > 
> > 
> > 看起来是刷新太频繁了，试试增加刷新间隔
> 
> 我也遇到这个错误，间隔调大了也没用，停了一段时间后运行第一次就这样报错

我这甚至可以一大半全在报错中间夹几条成功监控的
