### ISSUE TITLE
能否加速下单时间

### ISSUE THREAD

**Issue by ddv12138** [ToolGallery/APEStoreAssistant#17]
有没有可能加快下单时间，我连续用七台服务器跑了一个月，没有一次成功下单

大概有不下十几次检测到有货，但是下单过程中没了

**Comment by SajoLuo** [comment]
+1 深圳抢不到，到PickTime就结束了哈哈

**Comment by ddv12138** [comment]
今天突然提示抢到了，也顺利走完全程了下单成功提醒我检查邮箱，但是我邮箱啥也没有收到
<img width="806" alt="image" src="https://github.com/ToolGallery/APEStoreAssistant/assets/16048118/3da7d30f-da6d-40bb-851f-be94665d29fb">

**Comment by FreeIdom** [comment]
增加了下单池，速度应该快不少

**Comment by FreeIdom** [comment]
下单成功没提醒，目前猜测是没成功，需要再优化下流程

**Comment by FreeIdom** [comment]
#16

**Comment by ddv12138** [comment]
感谢
虽然我这边放货的同时，我之前下单的送货的刚好也发货了
